name: CI-CD with GitHub Actions
on: [ push ]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch:
          - master
        distro:
          - ubuntu-latest
        node-version: [ 17.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install modules
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Build storybook
        run: npm run build:storybook
      - name: Run unit tests
        run: npm run test:unit
      - name: Run e2e tests
        run: npm run test:e2e
      - name: Lint code
        run: npm run lint
